---
name: DeadLossMoney
version: 1.0.1
api:
- 5.0.0
main: KumaDev\DeadLossMoney\Main
author: KumaDeveloper
description: A plugin to reduce your money when you die
softdepend: [EconomyAPI, BedrockEconomy]
...
