# DeadLossMoney Configuration By KumaDev

# The message to be displayed when the player dies and respawns
death_message: "§cYou Lost Money §e{MONEY_LOSSMONEY} §cWhen Dead."

# Set the player will lose money when dead
money_lost_percentage: 0.05

# Message the player's remaining money
money_message: "§aYour remaining money is §e{YOUR_MONEY}."

# Choose the economy you use ("economyapi"/"bedrockeconomy")
economy:
  provider: "bedrockeconomy"